version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8077:30"
    volumes:
      - ./my_symfony_app:/var/www
    networks:
      - symfony

  web:
    image: nginx:alpine
    container_name: symfony_web
    volumes:
      - ./my_symfony_app:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8077:30"
    networks:
      - symfony

  db:
    image: mysql:5.7
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3301:3301"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
